package main

///
// Mandatory env vars
///

const (
	ENV_POSTGRES_USER     = "POSTGRES_USER"
	ENV_POSTGRES_PASSWORD = "POSTGRES_PASSWORD"
	ENV_POSTGRES_DB       = "POSTGRES_DB"
	ENV_POSTGRES_HOST     = "POSTGRES_HOST"
	ENV_POSTGRES_PORT     = "POSTGRES_PORT"
	ENV_API_PORT          = "API_PORT"
	ENV_POSTGRES_SCHEMA   = "POSTGRES_SCHEMA"
	ENV_MAX_FEATURE       = "MAX_FEATURE"
)

///
// Optional env vars
///

const ENV_VIEWER_URL = "VIEWER_URL"
const ENV_API_KEY = "API_KEY"
